name: github checkout

on:
  push:
    branches:
    - main
jobs:
  checkout-job:
    name: checkout source 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
